

public  class checkDataTypes {
    public void methodBoolean (){
        boolean checkBoolean=true;
        system.debug(checkBoolean);

    }

    public void  methodInteger (){
        integer varFirst= 1;
        integer varSecond= 2;
        system.debug (varFirst);
        system.debug (varSecond);



     }

     public void stringMethod(){

        string varName= 'Marufa';
        string var2Name= 'Sumi';

        system.debug (varName);
        system.debug (var2Name);


     }
    

}

   

    

