public class PrimitiveDataTypeDemo2 {
    public void print1(){
        //this is method body.
        Id id1 = '0015i00000BFSCtAAP';
        system.debug('print id = ' + id1);

        object obj1= 'This is a string';
        object obj2=15;
        object obj3='0015i00000BFSCtAAP';
        object obj4=true;
        system.debug (obj1);
        system.debug (obj2);
        system.debug (obj3);
        system.debug (obj4);
    }
}

